name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag traefik:$(date +%s)
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: github-actions-publish/publish-action@v1
        with: 
          tag: traefik:$(date +%s)
    
